version: "3"
services:
  mysql:
    image: mysql:8
    container_name: mysql_cognitus
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: